M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu24.04.1} date 2026-05-05T21:25:25+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-05T21:25:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X70.0Y-63.525
X70.0Y-68.525
T2
X38.5Y-62.25
X38.5Y-65.25
T3
X39.0Y-54.75
X39.5Y-82.5
X72.0Y-82.25
X72.161Y-54.75
M30
